apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ManikandanH/argo-cd.git
    targetRevision: HEAD
    path: sample
  destination:
    server: https://kubernetes.default.svc
    namespace: ps-staging
  syncPolicy:
    retry:
      limit: 2
    automated: 
        prune: true
        selfHeal: true
        allowEmpty: false 
    syncOptions:
      - CreateNamespace=true
      - Replace=true