apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-argo-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'ssh://git@github.com/ManikandanH/argo-cd.git'
    targetRevision: main
    path: sample
  destination:
    server: https://kubernetes.default.svc
    namespace: ps-staging
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true