apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.jenkins: webhook:jenkins
    notifications.argoproj.io/subscribe.on-sync-succeeded.gmail: itsmh0305@gmail.com
spec:
  destination:
    name: ''
    namespace: ps-staging
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s-config/ps
    repoURL: 'git@github.com:ManikandanH/helm.git'
    targetRevision: main
    helm:
      valueFiles:
        - values-staging-test.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
